# Generated by Django 5.2.3 on 2025-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('created_at',)},
        ),
    ]
